import "./globals.css";
import type { Metadata } from "next";

import Wrappers from "./wrapper";
export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 0.2,
    maximumScale: 1,
  },
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        <Wrappers> {children}</Wrappers>
      </body>
    </html>
  );
}
